version: "3.3"

services:
  db:
    image: postgres:13.2
    container_name: blend_example_db
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    depends_on: ["db"]

  deepseek:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama
    ports:
      - 11434:11434
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 2 && ollama pull deepseek-r1:1.5b && tail -f /dev/null"]
    extra_hosts:
      - "host.docker.internal:host-gateway"